---
swagger: "2.0"
info:
  description: Alexis Bravo's Missing periods public API
  version: 0.0.1
  title: Missing periods API
  termsOfService: http://swagger.io/terms/
  contact:
    email: alexis.ve@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 127.0.0.1:8087
basePath: /challenge
tags:
- name: periods
  description: Missing periods list
schemes:
- http
paths:
  /periods/missing-periods:
    get:
      tags:
      - periods
      summary: Missing periods list
      operationId: periods
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Period, received dates and missing dates
          schema:
            $ref: '#/definitions/Response'
definitions:
  Response:
    type: object
    properties:
      id:
        type: integer
        format: int64
      from:
        type: string
        format: date
      to:
        type: string
        format: date
      received_dates:
        type: array
        items:
          type: string
          format: date
      missing_dates:
        type: array
        items:
          type: string
          format: date
externalDocs:
  description: Especificación de swagger
  url: https://swagger.io/docs/specification/about/
